const palette = {
  background: '#F8F9FC',
  baseBackground: '#FFFFFF',
  sec_background: '#F0F2F5',
  surface: '#FFFFFF',
  textColor: '#1A1F36',
  secText: '#697386',
  border: '#E6E8F0',
  primary: '#9945FF',
  primaryDark: '#7B2CBF',
  success: '#14F195',
  error: '#FF4D4D',
  warning: '#FFB800',
} as const;

export const colors = {
  palette,
  transparent: 'rgba(0, 0, 0, 0)',
  background: palette.background,
  baseBackground: palette.baseBackground,
  secondaryBg: palette.sec_background,
  surface: palette.surface,
  text: palette.textColor,
  textDim: palette.secText,
  border: palette.border,
  primary: palette.primary,
  primaryDark: palette.primaryDark,
  success: palette.success,
  error: palette.error,
  warning: palette.warning,
} as const;
