const palette = {
  background: '#FAFAFA',
  baseBackground: '#FFFFFF',
  sec_background: '#F5F5F5',
  surface: '#FFFFFF',
  textColor: '#212121',
  secText: '#757575',
  border: '#EEEEEE',
  primary: '#732255',
  primaryDark: '#3700B3',
  success: '#4CAF50',
  error: '#F44336',
  warning: '#FFC107',
} as const;

export const colors = {
  palette,
  transparent: 'rgba(0, 0, 0, 0)',
  background: palette.background,
  baseBackground: palette.baseBackground,
  secondaryBg: palette.sec_background,
  surface: palette.surface,
  text: palette.textColor,
  textDim: palette.secText,
  border: palette.border,
  primary: palette.primary,
  primaryDark: palette.primaryDark,
  success: palette.success,
  error: palette.error,
  warning: palette.warning,
} as const;
